# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Coding/Vivado/project/project_23H/project_2PSK_3/project_2PSK_3.srcs/sources_1/bd/design_1/ip/design_1_demodulation_AM_0_0/design_1_demodulation_AM_0_0.xci
# IP: The module: 'design_1_demodulation_AM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/Coding/Vivado/project/project_23H/project_2PSK_3/project_2PSK_3.srcs/sources_1/ip/fir_compiler_high/fir_compiler_high.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_high || ORIG_REF_NAME==fir_compiler_high} -quiet] -quiet

# IP: D:/Coding/Vivado/project/project_23H/project_2PSK_3/project_2PSK_3.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet

# IP: D:/Coding/Vivado/project/project_23H/project_2PSK_3/project_2PSK_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: d:/Coding/Vivado/project/project_23H/project_2PSK_3/project_2PSK_3.srcs/sources_1/bd/design_1/ip/design_1_demodulation_AM_0_0/design_1_demodulation_AM_0_0.xci
# IP: The module: 'design_1_demodulation_AM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/Coding/Vivado/project/project_23H/project_2PSK_3/project_2PSK_3.srcs/sources_1/ip/fir_compiler_high/fir_compiler_high.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_high || ORIG_REF_NAME==fir_compiler_high} -quiet] -quiet

# IP: D:/Coding/Vivado/project/project_23H/project_2PSK_3/project_2PSK_3.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet

# IP: D:/Coding/Vivado/project/project_23H/project_2PSK_3/project_2PSK_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
